name: BitcoinBroker
main: de.shittyco.BitcoinBroker.BitcoinBroker
version: 1.0.20121109.0
softdepend: [Vault]
commands:
    btc:
        description: All BitcoinBroker commands.
        usage: '/btc [command] [args]
/btc brokerage - View brokerage information. 
/btc account [player] - View account information. 
/btc account [player] link [address] - Sets the linked BTC address for payouts. 
/btc sell [# coins] - Sells the specified number of coins for BTC.
/btc buy [# coins] - Buys the specified number of coins with BTC.
/btc transfer [# BTC] - Transfers the specified balance to the linked account. '
        permission: BitcoinBroker.btc
        permission-message: You do not have permission to trade BTC.
permissions:
    BitcoinBroker.btc:
        default: true
