name: BitcoinBroker
main: de.shittyco.BitcoinBroker.BitcoinBroker
version: 1.0.20121013.0
commands:
    account:
        description: Gets basic account information.
        usage: /account [player]
        permission: BitcoinBroker.account
        permission-message: You do not have permission to trade BTC.
    brokerage:
        description: Gets brokerage information configured on the server.
        usage: /brokerage 
        permission: BitcoinBroker.brokerage
        permission-message: You do not have permission to view brokerage rates.
permissions:
    BitcoinBroker.account:
        default: true
    BitcoinBroker.brokerage:
        default: true 