gods:
    ==: GodsSection
    redgod:
        ==: God 
        name: The Red God
        shrine:
            ==: Shrine
            construction: 100
            structure:
            sacrifices:
                Fish:
                    ==: Trade
                    item:
                        ==: org.bukkit.inventory.ItemStack
                        type: RAW_FISH
                    favor: 1
                RedFlower:
                    ==: Trade
                    item: 
                        ==: org.bukkit.inventory.ItemStack
                        type: RED_ROSE
                    favor: 2
            blessings:
                Redstone:
                    ==: Trade
                    item: 
                        ==: org.bukkit.inventory.ItemStack
                        type: REDSTONE
                    favor: 64
                Clay: 
                    ==: Trade
                    item: 
                        ==: org.bukkit.inventory.ItemStack
                        type: CLAY
                    favor: 16
                RedFlower:
                    ==: Trade
                    item: 
                        ==: org.bukkit.inventory.ItemStack
                        type: RED_ROSE
                    favor: 2
                RedDye:
                    ==: Trade
                    item: 
                        ==: org.bukkit.inventory.ItemStack
                        type: INK_SACK
                        damage: 1
                    favor: 1
    fortune:
        ==: God
        name: The God of Fortune
        shrine:
            ==: Shrine
            structure:
